name: Java CI Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install
    
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: OWASP Dependency Check
        continue-on-error: true
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -Ddependency-check.skipUpdates=true \
            -Ddependency-check.failOnError=false
  sonarcloud:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: SonarCloud Scan
          run: mvn verify sonar:sonar \
            -Dsonar.projectKey=soulaiman-bouali2 \
            -Dsonar.organization=SOULAIMAN-BOUALI2 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.02e0d2d6ecc5c386f71465809f96c24be95b6341 }}